from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('institutions/', views.institutions, name='institutions'),
    path('institutions/new/', views.institution_edit, name='institution_create'),
    path('institutions/<int:pk>/edit/', views.institution_edit, name='institution_edit'),
    path('references/', views.references, name='references'),
    path('references/new/', views.reference_edit, name='reference_create'),
    path('references/<uuid:pk>/', views.reference_detail, name='reference_detail'),
    path('references/<uuid:pk>/edit/', views.reference_edit, name='reference_edit'),
    path('references/<uuid:pk>/nodes/new/', views.reference_node, name='reference_node_create'),
    path('references/<uuid:pk>/nodes/<uuid:node_id>/edit/', views.reference_node, name='reference_node_edit'),
    path('references/<uuid:pk>/nodes/<uuid:node_id>/delete/', views.reference_action, {'action': 'delete_node'}, name='reference_node_delete'),
    path('references/<uuid:pk>/<str:action>/', views.reference_action, name='reference_action'),
    path('visits/new/', views.visit_create, name='visit_create'),
    path('visits/<uuid:pk>/', views.visit_detail, name='visit_detail'),
    path('visits/<uuid:pk>/action/<str:action>/', views.visit_action, name='visit_action'),
    path('visits/<uuid:pk>/finalize/<str:action>/', views.visit_finalize, name='visit_finalize'),
    path('visits/<uuid:pk>/local/', views.visit_local, name='visit_local'),
    path('visits/<uuid:pk>/local/<uuid:node_id>/', views.visit_local, name='visit_local_edit'),
    path('visits/<uuid:pk>/export/', views.visit_export, name='visit_export'),
    path('guides/', views.guides, name='guides'),
    path('guides/new/', views.guide_choose, name='guide_choose'),
    path('guides/new/<uuid:reference_id>/', views.guide_edit, name='guide_create'),
    path('guides/<uuid:pk>/edit/', views.guide_edit, name='guide_edit'),
    path('guides/<uuid:pk>/delete/', views.guide_delete, name='guide_delete'),
    path('submissions/', views.submissions, name='submissions'),
    path('submissions/<uuid:pk>/', views.submission_detail, name='submission_detail'),
    path('assignments/', views.assignments, name='assignments'),
    path('assignments/new/', views.assignment_choose, name='assignment_choose'),
    path('assignments/new/<uuid:visit_id>/', views.assignment_edit, name='assignment_create'),
    path('assignments/<uuid:pk>/', views.assignment_detail, name='assignment_detail'),
    path('assignments/<uuid:pk>/edit/', views.assignment_edit, name='assignment_edit'),
    path('assignments/<uuid:pk>/issue/', views.assignment_issue, name='assignment_issue'),
    path('assignments/<uuid:pk>/revoke/', views.assignment_revoke, name='assignment_revoke'),
]
