# Generated by Django 5.2.17 on 2026-09-20 15:38

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='اسم المؤسسة')),
                ('kind', models.CharField(blank=True, max_length=100, verbose_name='النوع')),
                ('active', models.BooleanField(default=True, verbose_name='نشطة')),
            ],
            options={
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'إدارة'), ('INSPECTOR', 'مفتش')], default='INSPECTOR', max_length=12)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=240, verbose_name='عنوان التكليف')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة إدارية'), ('ISSUED', 'صادر'), ('REVOKED', 'ملغى')], default='DRAFT', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_assignments', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issued_assignments', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_stable_id', models.UUIDField()),
                ('scope_locked', models.BooleanField(default=False, verbose_name='تثبيت النطاق')),
                ('completion_required', models.BooleanField(default=False, verbose_name='اشتراط الإنجاز')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='inspections.assignment')),
            ],
            options={
                'ordering': ['target_stable_id'],
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=240, verbose_name='اسم المرجع')),
                ('description', models.TextField(blank=True, verbose_name='تعريف المرجع')),
                ('visibility', models.CharField(choices=[('SHARED', 'مشترك'), ('PRIVATE', 'شخصي')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='references', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=240, verbose_name='اسم الدليل')),
                ('description', models.TextField(blank=True, verbose_name='وصف الدليل')),
                ('targets', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guides', to='inspections.reference')),
            ],
            options={
                'ordering': ['title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('BRANCH', 'فرع'), ('SPEC', 'وصف / مواصفة'), ('ITEM', 'بند فحص')], max_length=8, verbose_name='نوع العنصر')),
                ('title', models.CharField(max_length=300, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, verbose_name='التوضيح')),
                ('position', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='inspections.referencenode')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='inspections.reference')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_id', models.UUIDField()),
                ('snapshot', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'قيد المراجعة'), ('APPROVED', 'مقبول'), ('REJECTED', 'مرفوض')], default='PENDING', max_length=12)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('published_reference_id', models.UUIDField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution_snapshot', models.JSONField()),
                ('inspector_snapshot', models.JSONField()),
                ('date', models.DateField(verbose_name='تاريخ الزيارة')),
                ('source_reference_id', models.UUIDField(blank=True, null=True)),
                ('reference_snapshot', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('COMPLETED', 'مكتملة')], default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_payload', models.JSONField(blank=True, null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inspections.institution')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GuideApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_id', models.UUIDField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('snapshot', models.JSONField()),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('added', models.JSONField(default=list)),
                ('skipped', models.JSONField(default=list)),
                ('applied_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_applications', to='inspections.visit')),
            ],
            options={
                'ordering': ['applied_at', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='inspections.visit'),
        ),
        migrations.CreateModel(
            name='VisitNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stable_id', models.UUIDField(default=uuid.uuid4)),
                ('parent_stable_id', models.UUIDField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('BRANCH', 'فرع'), ('SPEC', 'وصف / مواصفة'), ('ITEM', 'بند فحص')], max_length=8)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('selected', models.BooleanField(default=False)),
                ('state', models.CharField(choices=[('ACTIVE', 'نشط'), ('EXCLUDED', 'مستبعد')], default='ACTIVE', max_length=8)),
                ('origin', models.CharField(blank=True, choices=[('LEGACY', 'موروث'), ('MANUAL', 'اختيار المفتش'), ('GUIDE', 'دليل اختياري'), ('ASSIGNMENT', 'تكليف رسمي'), ('LOCAL', 'محتوى محلي')], max_length=12)),
                ('local', models.BooleanField(default=False)),
                ('baseline_scope_locked', models.BooleanField(default=False)),
                ('baseline_completion_required', models.BooleanField(default=False)),
                ('result', models.CharField(blank=True, choices=[('CONFORMING', 'مطابق'), ('NONCONFORMING', 'غير مطابق'), ('NOT_APPLICABLE', 'غير منطبق')], max_length=16)),
                ('value', models.TextField(blank=True)),
                ('observation', models.TextField(blank=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='inspections.visit')),
            ],
            options={
                'ordering': ['position', 'stable_id'],
            },
        ),
        migrations.CreateModel(
            name='Obligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_locked', models.BooleanField(default=False)),
                ('completion_required', models.BooleanField(default=False)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligations', to='inspections.assignmententry')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligations', to='inspections.visitnode')),
            ],
        ),
        migrations.AddConstraint(
            model_name='assignmententry',
            constraint=models.UniqueConstraint(fields=('assignment', 'target_stable_id'), name='unique_assignment_target'),
        ),
        migrations.AddConstraint(
            model_name='assignmententry',
            constraint=models.CheckConstraint(condition=models.Q(('scope_locked', True), ('completion_required', True), _connector='OR'), name='entry_has_obligation'),
        ),
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('completed_payload__isnull', True), ('status', 'DRAFT')), models.Q(('completed_at__isnull', False), ('completed_payload__isnull', False), ('status', 'COMPLETED')), _connector='OR'), name='visit_completion_sealed'),
        ),
        migrations.AddConstraint(
            model_name='guideapplication',
            constraint=models.UniqueConstraint(fields=('visit', 'guide_id', 'fingerprint'), name='unique_guide_application'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('issued_at__isnull', True), ('revoked_at__isnull', True), ('status', 'DRAFT')), models.Q(('issued_at__isnull', False), ('revoked_at__isnull', True), ('status', 'ISSUED')), models.Q(('issued_at__isnull', False), ('revoked_at__isnull', False), ('status', 'REVOKED'), models.Q(('revocation_reason', ''), _negated=True)), _connector='OR'), name='assignment_audit_state'),
        ),
        migrations.AddConstraint(
            model_name='visitnode',
            constraint=models.UniqueConstraint(fields=('visit', 'stable_id'), name='unique_visit_stable_node'),
        ),
        migrations.AddConstraint(
            model_name='visitnode',
            constraint=models.CheckConstraint(condition=models.Q(('selected', False), models.Q(('origin', ''), _negated=True), _connector='OR'), name='selected_node_has_origin'),
        ),
        migrations.AddConstraint(
            model_name='visitnode',
            constraint=models.CheckConstraint(condition=models.Q(('kind', 'ITEM'), ('result', ''), _connector='OR'), name='result_only_on_items'),
        ),
        migrations.AddConstraint(
            model_name='visitnode',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'BRANCH'), _negated=True), ('baseline_completion_required', False), _connector='OR'), name='branch_not_completable'),
        ),
        migrations.AddConstraint(
            model_name='obligation',
            constraint=models.UniqueConstraint(fields=('entry', 'node'), name='unique_entry_node_obligation'),
        ),
    ]
